"""Typed GitHub Actions OIDC subject semantics.

The analyzer treats GitHub subjects as values generated by provider-level
constructors, not as arbitrary strings.  The default constructors are branch,
tag, pull-request, and environment.  Raw colons in metadata components are not
allowed in the normalized subject grammar; GitHub percent-encodes them in the
subject claim.
"""
from __future__ import annotations

import re
import json
from dataclasses import dataclass
from typing import Iterable, Optional, Sequence, Set, Tuple

from .regular import NFA, EPS, union, literal, intersect, union_globs, DEFAULT_ALPHABET, alphabet_from_patterns

# All singleton literals and finite exclusions used by the constructor NFAs.
# Including these boundaries makes every remaining code point indistinguishable
# to *both* the constructor predicates and the equality/glob predicates.
GITHUB_SUPPORT_LITERALS = (
    "repo:", "/", ":ref:refs/heads/", ":ref:refs/tags/",
    ":pull_request", ":environment:", "*?",
)
ORG_REPO_COMPONENT_RE = re.compile(r"[^/:*?]+")
COLON_FREE_COMPONENT_RE = re.compile(r"[^:*?]+")


def github_alphabet_from_patterns(*patterns: object, base: Sequence[str] = DEFAULT_ALPHABET) -> Tuple[str, ...]:
    """Complete support for the modeled typed constructor plus string patterns."""
    return alphabet_from_patterns(("equals", GITHUB_SUPPORT_LITERALS), *patterns, base=base)

@dataclass(frozen=True)
class SubjectAtom:
    owner: str
    repository: str
    kind: str
    value: str = ""

    @property
    def environment(self) -> str:
        return self.value if self.kind == "environment" else ""


def governance_key(owner: str, repository: str, environment: str) -> str:
    """Repository-scoped governance key used in certificates and reports."""
    return f"{owner}/{repository}:{environment}"


def parse_github_subject(subject: str) -> Optional[SubjectAtom]:
    """Parse the modeled default constructor; this is not live-provider validation."""
    if not isinstance(subject, str):
        return None
    if not subject.startswith("repo:"):
        return None
    body = subject[len("repo:"):]
    if "/" not in body:
        return None
    owner, rest = body.split("/", 1)
    if not ORG_REPO_COMPONENT_RE.fullmatch(owner):
        return None
    for marker, kind in ((":ref:refs/heads/", "branch"), (":ref:refs/tags/", "tag"), (":environment:", "environment")):
        if marker in rest:
            repo, value = rest.split(marker, 1)
            if not repo or not value:
                return None
            if not ORG_REPO_COMPONENT_RE.fullmatch(repo) or not COLON_FREE_COMPONENT_RE.fullmatch(value):
                return None
            return SubjectAtom(owner, repo, kind, value)
    suffix = ":pull_request"
    if rest.endswith(suffix):
        repo = rest[:-len(suffix)]
        if repo and ORG_REPO_COMPONENT_RE.fullmatch(repo):
            return SubjectAtom(owner, repo, "pull_request", "")
    return None


def is_github_subject(subject: str) -> bool:
    return parse_github_subject(subject) is not None


def _component_chars(alphabet: Sequence[str], *, allow_slash: bool) -> Tuple[str, ...]:
    blocked = {":", "*", "?"}
    if not allow_slash:
        blocked.add("/")
    return tuple(ch for ch in alphabet if ch not in blocked)


def _seq_plus(chars: Sequence[str], alphabet: Sequence[str]) -> NFA:
    """One-or-more occurrences of characters from chars."""
    n = NFA(start=0, finals={1}, alphabet=tuple(alphabet))
    n.states.update({0, 1})
    for ch in chars:
        n.add_edge(0, ch, 1)
        n.add_edge(1, ch, 1)
    return n


def _concat(parts: Sequence[NFA], alphabet: Sequence[str]) -> NFA:
    if not parts:
        return literal("", alphabet)
    out = NFA(start=0, finals=set(), alphabet=tuple(alphabet))
    out.states.add(0)
    offset = 0
    prev_finals = {0}
    first = True
    for part in parts:
        if first:
            remap = {s: s for s in part.states}
            out.states |= set(remap.values())
            for s, d in part.trans.items():
                for sym, ts in d.items():
                    for t in ts:
                        out.add_edge(remap[s], sym, remap[t])
            out.start = remap[part.start]
            prev_finals = {remap[s] for s in part.finals}
            offset = max(out.states) + 1
            first = False
        else:
            remap = {s: s + offset for s in part.states}
            for pf in prev_finals:
                out.add_edge(pf, EPS, remap[part.start])
            for s, d in part.trans.items():
                for sym, ts in d.items():
                    for t in ts:
                        out.add_edge(remap[s], sym, remap[t])
            prev_finals = {remap[s] for s in part.finals}
            offset = max(out.states) + 1
    out.finals = set(prev_finals)
    return out


def github_default_subject_nfa(alphabet: Sequence[str] = DEFAULT_ALPHABET) -> NFA:
    """NFA for the default GitHub Actions subject constructors.

    Owner/repository components exclude slash, colon, star and question mark;
    branch/tag/environment components exclude colon, star and question mark,
    but allow slash. All other Python code points remain in the abstract model.  This is the
    typed issuer language used for default GitHub OIDC subjects.
    """
    alph = tuple(alphabet)
    owner_repo = _seq_plus(_component_chars(alph, allow_slash=False), alph)
    ref_like = _seq_plus(_component_chars(alph, allow_slash=True), alph)
    common = [literal("repo:", alph), owner_repo, literal("/", alph), owner_repo]
    branch = _concat(common + [literal(":ref:refs/heads/", alph), ref_like], alph)
    tag = _concat(common + [literal(":ref:refs/tags/", alph), ref_like], alph)
    pr = _concat(common + [literal(":pull_request", alph)], alph)
    env = _concat(common + [literal(":environment:", alph), ref_like], alph)
    return union([branch, tag, pr, env], alph)


def issuer_subject_nfa(issuer_patterns: Sequence[str] | None,
                       alphabet: Sequence[str] = DEFAULT_ALPHABET) -> NFA:
    """Typed issuer language, optionally refined by user-supplied patterns."""
    base = github_default_subject_nfa(alphabet)
    if not issuer_patterns:
        return base
    return intersect(base, union_globs(list(issuer_patterns), alphabet), alphabet)


def exact_environment_from_pattern(pattern: str) -> Optional[SubjectAtom]:
    """Return an environment subject only when pattern is exact and typed."""
    if "*" in pattern or "?" in pattern:
        return None
    atom = parse_github_subject(pattern)
    return atom if atom and atom.kind == "environment" else None


def governance_set(raw: object) -> Set[Tuple[str, str, str]]:
    """Normalize repository-scoped governance facts.

    Accepted anonymous artifact encodings are dictionaries with owner/repository
    /environment fields, strings of the form owner/repository:environment, or
    strings of the form repo:owner/repository:environment:environment.
    Legacy unscoped names are intentionally not returned here.
    """
    out: Set[Tuple[str, str, str]] = set()
    if raw is None:
        return out
    items = raw if isinstance(raw, list) else [raw]
    for item in items:
        if isinstance(item, dict):
            owner = str(item.get("owner", item.get("org", "")))
            repo = str(item.get("repository", item.get("repo", "")))
            env = str(item.get("environment", item.get("env", "")))
            if owner and repo and env:
                out.add((owner, repo, env))
            continue
        text = str(item)
        if text.startswith("{"):
            try:
                obj = json.loads(text)
            except Exception:
                obj = None
            if isinstance(obj, dict):
                owner = str(obj.get("owner", obj.get("org", "")))
                repo = str(obj.get("repository", obj.get("repo", "")))
                env = str(obj.get("environment", obj.get("env", obj.get("name", ""))))
                if owner and repo and env:
                    out.add((owner, repo, env))
                    continue
        if text.startswith("repo:"):
            atom = parse_github_subject(text)
            if atom and atom.kind == "environment":
                out.add((atom.owner, atom.repository, atom.environment))
            continue
        if ":" in text and "/" in text.split(":", 1)[0]:
            left, env = text.split(":", 1)
            owner, repo = left.split("/", 1)
            if owner and repo and env:
                out.add((owner, repo, env))
    return out
