#!/usr/bin/env bash
set -euo pipefail
export FEDFENCE_GRID_PER="${FEDFENCE_GRID_PER:-128}"
export FEDFENCE_GRID_WORKERS="${FEDFENCE_GRID_WORKERS:-1}"
export FEDFENCE_GRID_TRANSPORT="${FEDFENCE_GRID_TRANSPORT:-1}"
export FEDFENCE_IAC_PER="${FEDFENCE_IAC_PER:-32}"
export FEDFENCE_IAC_WORKERS="${FEDFENCE_IAC_WORKERS:-1}"
export FEDFENCE_IAC_TRANSPORT="${FEDFENCE_IAC_TRANSPORT:-1}"
export FEDFENCE_BENCH_MAX="${FEDFENCE_BENCH_MAX:-64}"
export FEDFENCE_BENCH_REPS="${FEDFENCE_BENCH_REPS:-3}"
export FEDFENCE_META_PER="${FEDFENCE_META_PER:-128}"
export FEDFENCE_META_TRANSPORT="${FEDFENCE_META_TRANSPORT:-1}"
exec "$(cd "$(dirname "$0")" && pwd)/reproduce_all.sh"
